const data = {
    products: [
      {
        id: '1',
        name: 'Milk, lowfat',
        description: 'this is milk. its not that deep chief',
        WWEIA_category_number: 1006,
        category_1: 'DAIRY',
        category_2: 'LOWFAT MILK/YOGURT',
        category_3: 'Milk, lowfat',
      },
      {
        id: '2',
        name: 'Bread, white',
        description: 'lets get this bread',
        WWEIA_category_number: 1006,
        category_1: 'GRAINS',
        category_2: 'YEAST BREADS AND TORTILLAS',
        category_3: 'Yeast breads',
      },
      {
        id: '3',
        name: 'Pasta, spaghetti',
        description: 'mamma mia, this is spaghetti',
        WWEIA_category_number: 1006,
        category_1: 'GRAINS',
        category_2: 'RICE AND PASTA',
        category_3: 'Pasta, noodles, cooked grains',
      },
      {
        id: '4',
        name: 'Beans',
        description: 'me and the bois at 3 AM looking for BEANS',
        WWEIA_category_number: 1006,
        category_1: 'VEGETABLES',
        category_2: 'VEGETABLES (Incl. Beans and Peas, not Starchy)	',
        category_3: 'Beans, peas, legumes',
      },
      {
        id: '5',
        name: 'Milk, lowfat',
        description: 'this is milk. its not that deep chief',
        WWEIA_category_number: 1006,
        category_1: 'DAIRY',
        category_2: 'LOWFAT MILK/YOGURT',
        category_3: 'Milk, lowfat',
      },
      {
        id: '6',
        name: 'Bread, white',
        description: 'lets get this bread',
        WWEIA_category_number: 1006,
        category_1: 'GRAINS',
        category_2: 'YEAST BREADS AND TORTILLAS',
        category_3: 'Yeast breads',
      },
      {
        id: '7',
        name: 'Pasta, spaghetti',
        description: 'mamma mia, this is spaghetti',
        WWEIA_category_number: 1006,
        category_1: 'GRAINS',
        category_2: 'RICE AND PASTA',
        category_3: 'Pasta, noodles, cooked grains',
      },
      {
        id: '8',
        name: 'Beans',
        description: 'me and the bois at 3 AM looking for BEANS',
        WWEIA_category_number: 1006,
        category_1: 'VEGETABLES',
        category_2: 'VEGETABLES (Incl. Beans and Peas, not Starchy)	',
        category_3: 'Beans, peas, legumes',
      },
    ],
  };

  export default data;  