const data = {
    products: [
      {
        id: '1',
        name: 'Milk, lowfat',
        description: 'Lowfat 2% Milk - 1 Gallon Can (Assorted Brands)',
        WWEIA_category_number: 1006,
        category_1: 'DAIRY',
        category_2: 'LOWFAT MILK/YOGURT',
      },
      {
        id: '2',
        name: 'Bread, white',
        description: '1 loaf of White Bread',
        WWEIA_category_number: 1006,
        category_1: 'GRAINS',
        category_2: 'YEAST BREADS AND TORTILLAS',
      },
      {
        id: '3',
        name: 'Pasta, spaghetti',
        description: '1 lb Spaghetti Pasta (Barilla)',
        WWEIA_category_number: 1006,
        category_1: 'GRAINS',
        category_2: 'RICE AND PASTA',
      },
      {
        id: '4',
        name: 'Black Beans',
        description: 'Approx. 15 Oz Can of Black Beans (Assorted Brands)',
        WWEIA_category_number: 1006,
        category_1: 'VEGETABLES',
        category_2: 'VEGETABLES (Incl. Beans and Peas, not Starchy)	',
      },
      {
        id: '1',
        name: 'Milk, lowfat',
        description: 'Lowfat 2% Milk - Half-Gallon Can (Assorted Brands)',
        WWEIA_category_number: 1006,
        category_1: 'DAIRY',
        category_2: 'LOWFAT MILK/YOGURT',
      },
      {
        id: '2',
        name: 'Bread, white',
        description: '1 loaf of White Bread',
        WWEIA_category_number: 1006,
        category_1: 'GRAINS',
        category_2: 'YEAST BREADS AND TORTILLAS',
      },
      {
        id: '3',
        name: 'Pasta, spaghetti',
        description: '1 lb Spaghetti Pasta (Barilla)',
        WWEIA_category_number: 1006,
        category_1: 'GRAINS',
        category_2: 'RICE AND PASTA',
      },
      {
        id: '4',
        name: 'Beans',
        description: 'Approx. 15 Oz Can of Black Beans (Assorted Brands)',
        WWEIA_category_number: 1006,
        category_1: 'VEGETABLES',
        category_2: 'VEGETABLES (Incl. Beans and Peas, not Starchy)	',
      },
    ],
  };

  export default data;  